"""Tool: summarize_note

Reads a specific note file in full and returns an LLM-generated
summary. Unlike search_notes (which returns top-k chunks), this
gives a complete picture of one note — useful when the agent needs
to understand the full scope of a document rather than just the
chunks most similar to a query.

Example use case:
  Query: "Give me a complete overview of my RL notes"
  Agent: summarize_note("rl_basics.md")   <- reads the whole thing
  vs.
  Agent: search_notes("RL overview")      <- only gets 4 chunks,
                                             might miss key sections

The summary is generated by a second LLM call — this is what makes
this tool "expensive" (one extra Ollama call per invocation) and
why the agent should prefer search_notes for targeted lookups and
only call this when full coverage is needed.
"""

from pathlib import Path

from app.config import NOTES_DIR
from app.llm import generate


TOOL_DEFINITION = {
    "type": "function",
    "function": {
        "name": "summarize_note",
        "description": (
            "Read a specific note file in full and return a comprehensive "
            "summary of its content. Use this when you need complete coverage "
            "of one note — not just the most relevant chunks. "
            "Requires knowing the exact filename (use list_notes first if unsure). "
            "More expensive than search_notes — only call when you need the full picture."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string",
                    "description": (
                        "The note filename to summarize, e.g. 'rl_basics.md'. "
                        "Must be an exact filename from the notes directory."
                    ),
                },
            },
            "required": ["filename"],
        },
    },
}

SUMMARIZE_PROMPT = """You are summarizing a personal note. Provide a structured, comprehensive summary covering all main topics, key facts, and important details. Be specific — include concrete terms, numbers, and examples from the note.

Note filename: {filename}

Note content:
{content}

Summary:"""


def run(filename: str) -> dict:
    """Read and summarize a note file.

    Returns:
        {
            "filename": str,
            "summary": str,
            "char_count": int,   <- original note length
            "found": bool
        }
    """
    notes_dir = Path(NOTES_DIR)
    note_path = notes_dir / filename

    # Security: only allow files inside NOTES_DIR, no path traversal
    try:
        note_path = note_path.resolve()
        notes_dir_resolved = notes_dir.resolve()
        if not str(note_path).startswith(str(notes_dir_resolved)):
            return {"filename": filename, "found": False, "error": "Invalid filename"}
    except Exception:
        return {"filename": filename, "found": False, "error": "Invalid filename"}

    if not note_path.exists():
        # Try to be helpful — list what exists
        available = [p.name for p in notes_dir.glob("*.md")]
        return {
            "filename": filename,
            "found": False,
            "summary": "",
            "error": f"File not found. Available notes: {', '.join(available)}",
        }

    try:
        content = note_path.read_text(encoding="utf-8")
    except OSError as e:
        return {"filename": filename, "found": False, "error": str(e)}

    # Truncate very long notes to avoid blowing the context window
    # (~6000 chars is roughly 1500 tokens, well within llama3.2's 8k window)
    truncated = content[:6000]
    was_truncated = len(content) > 6000

    prompt = SUMMARIZE_PROMPT.format(filename=filename, content=truncated)
    result = generate(prompt)

    summary = result.answer
    if was_truncated:
        summary = "[Note truncated to 6000 chars for summarization]\n\n" + summary

    return {
        "filename": filename,
        "found": True,
        "summary": summary,
        "char_count": len(content),
        "prompt_tokens": result.prompt_tokens,
        "completion_tokens": result.completion_tokens,
    }


def format_for_llm(result: dict) -> str:
    """Format the tool result as text for the LLM's next context window."""
    if not result.get("found"):
        return f"Could not summarize {result['filename']!r}: {result.get('error', 'not found')}"

    return (
        f"Summary of {result['filename']!r} "
        f"({result['char_count']} chars original):\n\n"
        f"{result['summary']}"
    )
